services:
  - type: web
    name: expense-manager
    env: docker
    plan: free
    healthCheckPath: /
    buildCommand: docker build -t expense-manager .
    startCommand: docker run -p $PORT:8080 expense-manager
    envVars:
      - key: PORT
        value: 8080
